package api

const (
	RoutePluginInfo             = "/plugin-info"
	RouteSystemInfo             = "/system-info"
	RouteSiteStatus             = "/site-status"
	RouteServerStatus           = "/server-status"
	RouteWhosOnline             = "/whos-online"
	RouteSecurityScore          = "/security-score"
	RouteSecurityScoreChecks    = "/security-score/checks"
	RouteSecurityScoreRefresh   = "/security-score/refresh"
	RouteOptions                = "/options"
	RouteResetSettings          = "/reset-settings"
	RouteSettingsPurgeCache     = "/settings/purge-cache"
	RouteClearCache             = "/clear-cache"
	RouteSettings               = "/settings"
	RouteRegenerateDeactivation = "/regenerate-deactivation-url"
	RouteSaveRecoveryURL        = "/save-recovery-url"
	RouteTFAStatus              = "/2fa/status"
	RouteTFAProvider            = "/2fa/provider"
	RouteTFABackupCodesStatus   = "/2fa/backup-codes/status"
	RouteTFAEmailStatus         = "/2fa/email/status"
	RouteTFAEmailSendCode       = "/2fa/email/send-code"
	RouteTFAEmailVerify         = "/2fa/email/verify"
	RouteTFAEmailDisable        = "/2fa/email/disable"
	RouteTFATOTPStatus          = "/2fa/totp/status"
	RouteTFATOTPSetup           = "/2fa/totp/setup"
	RouteTFATOTPVerify          = "/2fa/totp/verify"
	RouteTFATOTPDisable         = "/2fa/totp/disable"
	RouteTFAHOTPStatus          = "/2fa/hotp/status"
	RouteTFAHOTPSetup           = "/2fa/hotp/setup"
	RouteTFAHOTPVerify          = "/2fa/hotp/verify"
	RouteTFAHOTPDisable         = "/2fa/hotp/disable"
	RouteAuditLogs              = "/audit-logs"
	RouteAuditLogStats          = "/audit-logs/stats"
	RouteAuditLogEventTypes     = "/audit-logs/event-types"
	RouteAuditLogCleanup        = "/audit-logs/cleanup"
	RouteGetLoginFailedLogs     = "/get-login-failed-logs"
)
